using Dynomax.Application.ProjectContext;
using Dynomax.Application.ProjectContext.Repositories;
using Dynomax.Domain.ProjectContext;
using Dynomax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Dynomax.Infrastructure.ProjectContext.Repositories;

internal sealed class RepositoryHistoryService : IRepositoryHistoryService
{
    private readonly DynomaxDbContext _db; private readonly IRepositoryHistoryProviderClient _provider;
    public RepositoryHistoryService(DynomaxDbContext db,IRepositoryHistoryProviderClient provider){_db=db;_provider=provider;}

    public async Task<IReadOnlyList<RepositoryBranchSummary>> ListBranchesAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,int page,int pageSize,CancellationToken ct=default){Bounds(page,pageSize);Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return Array.Empty<RepositoryBranchSummary>();var branches=await _provider.ListBranchesAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,page,pageSize,ct);return branches.Select(x=>new RepositoryBranchSummary(x.Name,x.CommitSha,x.Protected,string.Equals(x.Name,t.Repository.DefaultBranch,StringComparison.Ordinal),IsStale(t.Repository,x.Name,x.CommitSha))).ToArray();}
    public async Task<RepositoryBranchDetail?> GetBranchAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,string branch,CancellationToken ct=default){Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return null;string name=RefName(branch);RepositoryProviderBranchDetail b=await _provider.GetBranchAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,name,ct);return new RepositoryBranchDetail(b.Name,b.CommitSha,b.Protected,string.Equals(b.Name,t.Repository.DefaultBranch,StringComparison.Ordinal),IsStale(t.Repository,b.Name,b.CommitSha),b.Rules);}
    public async Task<IReadOnlyList<RepositoryTagSummary>> ListTagsAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,int page,int pageSize,CancellationToken ct=default){Bounds(page,pageSize);Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return Array.Empty<RepositoryTagSummary>();var tags=await _provider.ListTagsAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,page,pageSize,ct);return tags.Select(x=>new RepositoryTagSummary(x.Name,x.CommitSha)).ToArray();}
    public async Task<RepositoryResolvedRef?> ResolveRefAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,string refType,string value,CancellationToken ct=default){Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return null;string type=refType?.Trim().ToLowerInvariant()??string.Empty;if(type=="commit")return new RepositoryResolvedRef("Commit",Sha(value),Sha(value),false);if(type=="branch"){RepositoryProviderBranchDetail b=await _provider.GetBranchAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,RefName(value),ct);return new RepositoryResolvedRef("Branch",b.Name,b.CommitSha,true);}if(type=="tag"){string tag=RefName(value);for(int page=1;page<=10;page++){var tags=await _provider.ListTagsAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,page,RepositoryHistoryLimits.MaxPageSize,ct);RepositoryProviderTag? match=tags.SingleOrDefault(x=>string.Equals(x.Name,tag,StringComparison.Ordinal));if(match is not null)return new RepositoryResolvedRef("Tag",match.Name,match.CommitSha,true);if(tags.Count<RepositoryHistoryLimits.MaxPageSize)break;}throw NotFound("Repository tag was not found.");}throw InvalidRef("refType must be Branch, Tag or Commit.");}
    public async Task<RepositoryCommitPage> ListCommitsAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,string? commitSha,string? path,int page,int pageSize,CancellationToken ct=default){Bounds(page,pageSize);Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return new RepositoryCommitPage(repoId,t.Repository.FullName,string.Empty,NormalizePath(path,true),page,pageSize,false,Array.Empty<RepositoryCommitSummary>());string sha=ShaRequired(commitSha);string normalized=NormalizePath(path,true);var commits=await _provider.ListCommitsAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,sha,normalized.Length==0?null:normalized,page,pageSize,ct);return new RepositoryCommitPage(repoId,t.Repository.FullName,sha,normalized.Length==0?null:normalized,page,pageSize,commits.Count==pageSize,commits.Select(Summary).ToArray());}
    public async Task<RepositoryCommitDetail?> GetCommitAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,string? commitSha,CancellationToken ct=default){Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return null;RepositoryProviderCommit c=await _provider.GetCommitAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,ShaRequired(commitSha),ct);return Detail(c);}
    public async Task<RepositoryCompareResult?> CompareAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,string? baseSha,string? headSha,CancellationToken ct=default){Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return null;string b=ShaRequired(baseSha),h=ShaRequired(headSha);RepositoryProviderCompare c=await _provider.CompareAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,b,h,ct);return new RepositoryCompareResult(repoId,t.Repository.FullName,b,h,c.Status,c.AheadBy,c.BehindBy,c.TotalCommits,c.Commits.Select(Summary).ToArray(),c.Files,c.CommitsTruncated,c.FilesTruncated,c.UnifiedDiff,c.UnifiedDiffTruncated);}
    public async Task<RepositoryBlameResult?> GetBlameAsync(ProjectContextRequestAccess access,Guid envId,Guid repoId,string? commitSha,string path,CancellationToken ct=default){Target t=await LoadAsync(access,repoId,ct);if(IsEmpty(t.Repository))return null;string sha=ShaRequired(commitSha),canonical=NormalizePath(path,false);RepositoryProviderBlame b=await _provider.GetBlameAsync(access.ProjectId,envId,t.Repository.CredentialSecretReferenceId,t.Repository.Owner,t.Repository.Name,sha,canonical,ct);int lines=b.Ranges.Sum(x=>Math.Max(0,x.EndingLine-x.StartingLine+1));return new RepositoryBlameResult(repoId,t.Repository.FullName,sha,canonical,b.Ranges.Count,lines,b.Truncated,b.Ranges);}

    private async Task<Target> LoadAsync(ProjectContextRequestAccess access,Guid repoId,CancellationToken ct){RequireRead(access);Guid? sourceId=await _db.ProjectContextSources.AsNoTracking().Where(x=>x.ProjectId==access.ProjectId&&x.SourceType==ProjectContextSourceTypes.GitRepositories).Select(x=>(Guid?)x.Id).SingleOrDefaultAsync(ct);if(!sourceId.HasValue)throw NotFound("Repository context was not found.");ProjectContextRepository? repo=await _db.ProjectContextRepositories.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==repoId&&x.SourceId==sourceId.Value&&x.IsActive,ct);if(repo is null)throw NotFound("Repository context was not found.");ProjectContextRepositoryPolicy? policy=await _db.ProjectContextRepositoryPolicies.AsNoTracking().SingleOrDefaultAsync(x=>x.RepositoryContextId==repoId,ct);if(policy is null)throw NotFound("Repository policy was not found.");if(!policy.AllowRead)throw new RepositoryHistoryException(RepositoryHistoryErrorCodes.PolicyDenied,"Repository history read is denied by effective repository policy.");if(!string.Equals(repo.Provider,"GitHub",StringComparison.OrdinalIgnoreCase))throw InvalidRef("Repository provider is not supported by this history surface.");return new Target(repo,policy);}
    private static bool IsEmpty(ProjectContextRepository r)=>r.HealthStatus==RepositoryConnectionHealthStates.Empty&&r.DefaultBranchHeadSha is null;
    private static bool IsStale(ProjectContextRepository r,string branch,string sha)=>string.Equals(branch,r.DefaultBranch,StringComparison.Ordinal)&&!string.IsNullOrWhiteSpace(r.DefaultBranchHeadSha)&&!string.Equals(r.DefaultBranchHeadSha,sha,StringComparison.OrdinalIgnoreCase);
    private static RepositoryCommitSummary Summary(RepositoryProviderCommit c)=>new(c.Sha,Headline(c.Message),c.CommittedAtUtc,c.AuthorName,c.AuthorEmail,c.ParentShas);
    private static RepositoryCommitDetail Detail(RepositoryProviderCommit c)=>new(c.Sha,c.Message,c.CommittedAtUtc,c.AuthorName,c.AuthorEmail,c.ParentShas,c.Additions,c.Deletions,c.TotalChanges,c.Files,c.FilesTruncated);
    private static string Headline(string value){string v=value??string.Empty;int i=v.IndexOfAny(new[]{'\r','\n'});return i<0?v:v[..i];}
    private static void Bounds(int page,int size){if(page<1||page>100000||size<1||size>RepositoryHistoryLimits.MaxPageSize)throw InvalidPaging("History paging is outside the allowed bounds.");}
    private static string ShaRequired(string? value){if(string.IsNullOrWhiteSpace(value))throw new RepositoryHistoryException(RepositoryHistoryErrorCodes.InvalidCommit,"An exact immutable commit SHA is required.");return Sha(value);}
    private static string Sha(string value){string s=value.Trim().ToLowerInvariant();if(s.Length is not(40 or 64)||s.Any(c=>!Uri.IsHexDigit(c)))throw new RepositoryHistoryException(RepositoryHistoryErrorCodes.InvalidCommit,"An exact 40- or 64-character hexadecimal commit SHA is required.");return s;}
    private static string RefName(string? value){string v=value?.Trim()??string.Empty;if(v.Length is<1 or>255||v.StartsWith('/')||v.EndsWith('/')||v.Contains("..",StringComparison.Ordinal)||v.Contains('\\')||v.Contains('~')||v.Contains('^')||v.Contains(':')||v.Contains('?')||v.Contains('*')||v.Contains('[')||v.Contains('\0')||v.Contains('\r')||v.Contains('\n'))throw InvalidRef("Repository ref name is invalid.");return v;}
    private static string NormalizePath(string? value,bool allowEmpty){string p=value?.Trim()??string.Empty;if(p.Length==0){if(allowEmpty)return string.Empty;throw InvalidPath("A canonical repository path is required.");}if(p.Length>1024||p.StartsWith('/')||p.Contains('\\')||p.Contains('\0')||p.Contains('\r')||p.Contains('\n'))throw InvalidPath("Repository path must be a bounded canonical relative Git path.");string[] segments=p.Split('/',StringSplitOptions.None);if(segments.Any(x=>x.Length==0||x is "." or ".."))throw InvalidPath("Repository path traversal and empty segments are not allowed.");return string.Join('/',segments);}
    private static void RequireRead(ProjectContextRequestAccess a){if(a.ProjectId==Guid.Empty||a.ActorUserId==Guid.Empty||!a.CanRead)throw new UnauthorizedAccessException("Project Context read access is required.");}
    private static RepositoryHistoryException NotFound(string m)=>new(RepositoryHistoryErrorCodes.NotFound,m);private static RepositoryHistoryException InvalidRef(string m)=>new(RepositoryHistoryErrorCodes.InvalidRef,m);private static RepositoryHistoryException InvalidPath(string m)=>new(RepositoryHistoryErrorCodes.InvalidPath,m);private static RepositoryHistoryException InvalidPaging(string m)=>new(RepositoryHistoryErrorCodes.InvalidPaging,m);
    private sealed record Target(ProjectContextRepository Repository,ProjectContextRepositoryPolicy Policy);
}