using System.Data;
using System.Text.Json;
using Dynomax.Application.ProjectContext;
using Dynomax.Application.ProjectContext.Repositories;
using Dynomax.Domain.ProjectContext;
using Dynomax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
namespace Dynomax.Infrastructure.ProjectContext.Repositories;

internal sealed class RepositoryConnectionService : IRepositoryConnectionService
{
 private readonly DynomaxDbContext _db; private readonly IRepositoryProviderClient _provider;
 public RepositoryConnectionService(DynomaxDbContext db,IRepositoryProviderClient provider){_db=db;_provider=provider;}
 public async Task<IReadOnlyList<RepositoryConnectionSummary>> ListAsync(ProjectContextRequestAccess access,bool includeInactive,CancellationToken cancellationToken=default){RequireRead(access);var source=await _db.ProjectContextSources.AsNoTracking().SingleOrDefaultAsync(x=>x.ProjectId==access.ProjectId&&x.SourceType==ProjectContextSourceTypes.GitRepositories,cancellationToken);if(source is null)return Array.Empty<RepositoryConnectionSummary>();var repos=await _db.ProjectContextRepositories.AsNoTracking().Where(x=>x.SourceId==source.Id&&(includeInactive||x.IsActive)).OrderBy(x=>x.Role).ThenBy(x=>x.FullName).ToListAsync(cancellationToken);var ids=repos.Select(x=>x.Id).ToArray();var policies=await _db.ProjectContextRepositoryPolicies.AsNoTracking().Where(x=>ids.Contains(x.RepositoryContextId)).ToDictionaryAsync(x=>x.RepositoryContextId,cancellationToken);return repos.Select(x=>ToSummary(x,policies.GetValueOrDefault(x.Id))).ToArray();}
 public async Task<RepositoryConnectionSummary> GetAsync(ProjectContextRequestAccess access,Guid repositoryContextId,CancellationToken cancellationToken=default){RequireRead(access);var pair=await LoadAsync(access.ProjectId,repositoryContextId,true,cancellationToken);return ToSummary(pair.Repository,pair.Policy);}
 public async Task<RepositoryValidationResult> ValidateAsync(ProjectContextRequestAccess access,Guid projectEnvironmentId,string repositoryUrl,Guid credentialSecretReferenceId,CancellationToken cancellationToken=default){RequireManage(access);if(projectEnvironmentId==Guid.Empty||credentialSecretReferenceId==Guid.Empty)throw Invalid("Environment and credential reference are required.");RepositoryProviderIdentity identity=_provider.CanonicalizeReference(repositoryUrl);RepositoryProviderRepository repo=await _provider.DiscoverRepositoryAsync(access.ProjectId,projectEnvironmentId,credentialSecretReferenceId,identity.Owner,identity.Name,cancellationToken);return ToValidation(repo);}
 public async Task<ConnectRepositoryResult> ConnectAsync(ProjectContextRequestAccess access,ConnectRepositoryCommand command,CancellationToken cancellationToken=default){RequireManage(access);RepositoryValidationResult v=await ValidateAsync(access,command.ProjectEnvironmentId,command.RepositoryUrl,command.CredentialSecretReferenceId,cancellationToken);DateTime now=DateTime.UtcNow;await using var tx=await _db.Database.BeginTransactionAsync(IsolationLevel.Serializable,cancellationToken);var source=await _db.ProjectContextSources.SingleOrDefaultAsync(x=>x.ProjectId==access.ProjectId&&x.SourceType==ProjectContextSourceTypes.GitRepositories,cancellationToken);if(source is null){source=new ProjectContextSource(access.ProjectId,ProjectContextSourceTypes.GitRepositories,"GitHub repositories","GitHub repository connections. Repository source bodies remain authoritative in GitHub.",true,access.ActorUserId,now);_db.ProjectContextSources.Add(source);await _db.SaveChangesAsync(cancellationToken);}var existing=await _db.ProjectContextRepositories.SingleOrDefaultAsync(x=>x.SourceId==source.Id&&x.Provider==_provider.Provider&&x.ProviderRepositoryId==v.ProviderRepositoryId,cancellationToken);bool created=false,reactivated=false,already=false;ProjectContextRepository repo;ProjectContextRepositoryPolicy policy;if(existing is null){repo=new ProjectContextRepository(source.Id,_provider.Provider,v.ProviderRepositoryId,v.Owner,v.Name,v.FullName,v.WebUrl,v.CloneUrl,v.Visibility,v.IsArchived,v.IsDisabled,v.IsFork,v.Description,NormalizeOptional(command.Role,100),NormalizeOptional(command.Purpose,1000),SerializeTags(command.Tags),v.DefaultBranch,v.DefaultBranchHeadSha,v.DefaultTreeSha,command.CredentialSecretReferenceId,access.ActorUserId,now);ApplyProviderSnapshot(repo,v,access.ActorUserId,now);_db.ProjectContextRepositories.Add(repo);policy=new ProjectContextRepositoryPolicy(repo.Id,access.ActorUserId,now);_db.ProjectContextRepositoryPolicies.Add(policy);created=true;}else{repo=existing;policy=await _db.ProjectContextRepositoryPolicies.SingleAsync(x=>x.RepositoryContextId==repo.Id,cancellationToken);if(repo.IsActive){if(repo.CredentialSecretReferenceId!=command.CredentialSecretReferenceId)throw new RepositoryConnectionException(RepositoryConnectionErrorCodes.Duplicate,"This GitHub repository is already connected with a different credential reference. Use update instead of creating a duplicate connection.");already=true;}else{repo.SetCredentialSecretReference(command.CredentialSecretReferenceId,access.ActorUserId,now);repo.SetContextMetadata(NormalizeOptional(command.Role,100),NormalizeOptional(command.Purpose,1000),SerializeTags(command.Tags),access.ActorUserId,now);repo.SetActive(true,HealthFor(v),access.ActorUserId,now);reactivated=true;}ApplyProviderSnapshot(repo,v,access.ActorUserId,now);}await SaveAsync(cancellationToken);await tx.CommitAsync(cancellationToken);return new ConnectRepositoryResult(ToSummary(repo,policy),created,reactivated,already);}
 public async Task<RepositoryConnectionSummary> RefreshAsync(ProjectContextRequestAccess access,Guid projectEnvironmentId,Guid repositoryContextId,CancellationToken cancellationToken=default){RequireManage(access);var pair=await LoadAsync(access.ProjectId,repositoryContextId,false,cancellationToken);var repo=pair.Repository;DateTime now=DateTime.UtcNow;try{RepositoryProviderRepository remote=await _provider.DiscoverRepositoryAsync(access.ProjectId,projectEnvironmentId,repo.CredentialSecretReferenceId,repo.Owner,repo.Name,cancellationToken);if(remote.ProviderRepositoryId!=repo.ProviderRepositoryId)throw Invalid("GitHub repository identity changed unexpectedly.");repo.SetProviderSnapshot(remote.Owner,remote.Name,remote.FullName,remote.WebUrl,remote.CloneUrl,remote.Visibility,remote.IsArchived,remote.IsDisabled,remote.IsFork,remote.Description,remote.DefaultBranch,remote.DefaultBranchHeadSha,remote.DefaultTreeSha,remote.IsEmpty?RepositoryConnectionHealthStates.Empty:RepositoryConnectionHealthStates.Healthy,null,now,now,access.ActorUserId,now);}catch(RepositoryProviderException ex){repo.SetRefreshState(repo.DefaultBranch,repo.DefaultBranchHeadSha,repo.DefaultTreeSha,RepositoryConnectionHealthStates.Error,ex.Code,null,now,access.ActorUserId,now);}await SaveAsync(cancellationToken);return ToSummary(repo,pair.Policy);}
 public async Task<IReadOnlyList<RepositoryConnectionSummary>> RefreshAllAsync(ProjectContextRequestAccess access,Guid projectEnvironmentId,CancellationToken cancellationToken=default){RequireManage(access);var current=await ListAsync(access,false,cancellationToken);var result=new List<RepositoryConnectionSummary>(current.Count);foreach(var item in current)result.Add(await RefreshAsync(access,projectEnvironmentId,item.RepositoryContextId,cancellationToken));return result;}
 public async Task<RepositoryConnectionSummary> UpdateAsync(ProjectContextRequestAccess access,Guid repositoryContextId,UpdateRepositoryConnectionCommand command,CancellationToken cancellationToken=default){RequireManage(access);var pair=await LoadAsync(access.ProjectId,repositoryContextId,false,cancellationToken);ApplyExpectedRowVersion(pair.Repository,command.ExpectedConcurrencyToken);DateTime now=DateTime.UtcNow;if(command.CredentialSecretReferenceId.HasValue&&command.CredentialSecretReferenceId.Value!=pair.Repository.CredentialSecretReferenceId){RepositoryProviderRepository remote=await _provider.DiscoverRepositoryAsync(access.ProjectId,command.ProjectEnvironmentId,command.CredentialSecretReferenceId.Value,pair.Repository.Owner,pair.Repository.Name,cancellationToken);if(remote.ProviderRepositoryId!=pair.Repository.ProviderRepositoryId)throw Invalid("The replacement credential resolved a different repository identity.");pair.Repository.SetCredentialSecretReference(command.CredentialSecretReferenceId.Value,access.ActorUserId,now);pair.Repository.SetProviderSnapshot(remote.Owner,remote.Name,remote.FullName,remote.WebUrl,remote.CloneUrl,remote.Visibility,remote.IsArchived,remote.IsDisabled,remote.IsFork,remote.Description,remote.DefaultBranch,remote.DefaultBranchHeadSha,remote.DefaultTreeSha,remote.IsEmpty?RepositoryConnectionHealthStates.Empty:RepositoryConnectionHealthStates.Healthy,null,now,now,access.ActorUserId,now);}pair.Repository.SetContextMetadata(NormalizeOptional(command.Role,100),NormalizeOptional(command.Purpose,1000),SerializeTags(command.Tags),access.ActorUserId,now);RepositoryPolicyUpdate p=command.Policy;pair.Policy.UpdateSafeSettings(p.AllowRead,p.AllowWorkspace,p.AllowCommitPush,p.AllowPullRequest,p.AllowMerge,p.AllowRemoteBranchDelete,p.AllowActionsRerun,p.AllowDirectDefaultBranchWrite,p.AllowForcePush,p.RequirePullRequestForDefaultBranch,SerializePatterns(p.AllowedTargetBranchPatterns),SerializePatterns(p.AllowedBaseBranchPatterns),NormalizePrefix(p.AgentBranchPrefix),access.ActorUserId,now);await SaveAsync(cancellationToken);return ToSummary(pair.Repository,pair.Policy);}
 public async Task<RepositoryConnectionSummary> DisconnectAsync(ProjectContextRequestAccess access,Guid repositoryContextId,string expectedConcurrencyToken,CancellationToken cancellationToken=default){RequireManage(access);var pair=await LoadAsync(access.ProjectId,repositoryContextId,true,cancellationToken);ApplyExpectedRowVersion(pair.Repository,expectedConcurrencyToken);pair.Repository.SetActive(false,RepositoryConnectionHealthStates.Disconnected,access.ActorUserId,DateTime.UtcNow);await SaveAsync(cancellationToken);return ToSummary(pair.Repository,pair.Policy);}
 private async Task<(ProjectContextRepository Repository,ProjectContextRepositoryPolicy Policy)> LoadAsync(Guid projectId,Guid id,bool includeInactive,CancellationToken ct){var sourceId=await _db.ProjectContextSources.AsNoTracking().Where(x=>x.ProjectId==projectId&&x.SourceType==ProjectContextSourceTypes.GitRepositories).Select(x=>(Guid?)x.Id).SingleOrDefaultAsync(ct);if(!sourceId.HasValue)throw Missing();var repo=await _db.ProjectContextRepositories.SingleOrDefaultAsync(x=>x.Id==id&&x.SourceId==sourceId.Value&&(includeInactive||x.IsActive),ct);if(repo is null)throw Missing();var policy=await _db.ProjectContextRepositoryPolicies.SingleAsync(x=>x.RepositoryContextId==id,ct);return(repo,policy);}
 private void ApplyExpectedRowVersion(ProjectContextRepository repo,string token){if(string.IsNullOrWhiteSpace(token))throw new RepositoryConnectionException(RepositoryConnectionErrorCodes.ConcurrencyConflict,"A repository concurrency token is required.");byte[] bytes;try{bytes=Convert.FromBase64String(token);}catch(FormatException){throw new RepositoryConnectionException(RepositoryConnectionErrorCodes.ConcurrencyConflict,"The repository concurrency token is invalid.");}if(bytes.Length==0)throw new RepositoryConnectionException(RepositoryConnectionErrorCodes.ConcurrencyConflict,"The repository concurrency token is invalid.");_db.Entry(repo).Property(x=>x.RowVersion).OriginalValue=bytes;}
 private async Task SaveAsync(CancellationToken ct){try{await _db.SaveChangesAsync(ct);}catch(DbUpdateConcurrencyException){throw new RepositoryConnectionException(RepositoryConnectionErrorCodes.ConcurrencyConflict,"The repository connection changed since it was read. Refresh it and retry with the new concurrency token.");}}
 private static void ApplyProviderSnapshot(ProjectContextRepository r,RepositoryValidationResult v,Guid actor,DateTime now)=>r.SetProviderSnapshot(v.Owner,v.Name,v.FullName,v.WebUrl,v.CloneUrl,v.Visibility,v.IsArchived,v.IsDisabled,v.IsFork,v.Description,v.DefaultBranch,v.DefaultBranchHeadSha,v.DefaultTreeSha,HealthFor(v),null,now,now,actor,now);
 private static string HealthFor(RepositoryValidationResult v)=>v.IsEmpty?RepositoryConnectionHealthStates.Empty:RepositoryConnectionHealthStates.Healthy;
 private static RepositoryValidationResult ToValidation(RepositoryProviderRepository x)=>new("GitHub",x.ProviderRepositoryId,x.Owner,x.Name,x.FullName,x.WebUrl,x.CloneUrl,x.Visibility,x.IsArchived,x.IsDisabled,x.IsFork,x.Description,x.IsEmpty,x.DefaultBranch,x.DefaultBranchHeadSha,x.DefaultTreeSha,x.Capabilities,x.BranchRules,x.RateLimit);
 private static RepositoryConnectionSummary ToSummary(ProjectContextRepository r,ProjectContextRepositoryPolicy? p)=>new(r.Id,r.SourceId,r.Provider,r.ProviderRepositoryId,r.Owner,r.Name,r.FullName,r.WebUrl,r.CloneUrl,r.Visibility,r.IsArchived,r.IsDisabled,r.IsFork,r.ProviderDescription,r.Role,r.Purpose,ParseArray(r.TagsJson),r.DefaultBranch,r.DefaultBranchHeadSha,r.DefaultTreeSha,r.CredentialSecretReferenceId,r.HealthStatus,r.LastErrorCode,r.LastValidatedAtUtc,r.LastRefreshedAtUtc,r.IsActive,Convert.ToBase64String(r.RowVersion),ToPolicy(p));
 private static RepositoryPolicySnapshot ToPolicy(ProjectContextRepositoryPolicy? p)=>p is null?new(true,true,true,true,false,false,false,false,false,true,Array.Empty<string>(),Array.Empty<string>(),"dynomax/"):new(p.AllowRead,p.AllowWorkspace,p.AllowCommitPush,p.AllowPullRequest,p.AllowMerge,p.AllowRemoteBranchDelete,p.AllowActionsRerun,p.AllowDirectDefaultBranchWrite,p.AllowForcePush,p.RequirePullRequestForDefaultBranch,ParseArray(p.AllowedTargetBranchPatternsJson),ParseArray(p.AllowedBaseBranchPatternsJson),p.AgentBranchPrefix);
 private static IReadOnlyList<string> ParseArray(string json){try{return JsonSerializer.Deserialize<string[]>(json)??Array.Empty<string>();}catch(JsonException){return Array.Empty<string>();}}
 private static string SerializeTags(IReadOnlyList<string>? v)=>JsonSerializer.Serialize(NormalizeList(v,50,100)); private static string SerializePatterns(IReadOnlyList<string>? v)=>JsonSerializer.Serialize(NormalizeList(v,20,200));
 private static string[] NormalizeList(IReadOnlyList<string>? v,int maxItems,int maxLength){var r=v?.Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x.Trim()).Distinct(StringComparer.OrdinalIgnoreCase).ToArray()??Array.Empty<string>();if(r.Length>maxItems||r.Any(x=>x.Length>maxLength))throw Invalid("Repository metadata collection exceeds its bounded limits.");return r;}
 private static string? NormalizeOptional(string? v,int max){string? n=string.IsNullOrWhiteSpace(v)?null:v.Trim();if(n?.Length>max)throw Invalid("Repository metadata value is too long.");return n;}
 private static string NormalizePrefix(string v){string n=v?.Trim()??string.Empty;if(n.Length==0||n.Length>100||n.Contains("..",StringComparison.Ordinal)||n.StartsWith('/')||n.Contains('\\'))throw new RepositoryConnectionException(RepositoryConnectionErrorCodes.InvalidPolicy,"Repository branch prefix is invalid.");return n.EndsWith('/')?n:n+"/";}
 private static void RequireRead(ProjectContextRequestAccess a){if(a.ProjectId==Guid.Empty||a.ActorUserId==Guid.Empty||!a.CanRead)throw new UnauthorizedAccessException("Project Context read access is required.");}
 private static void RequireManage(ProjectContextRequestAccess a){RequireRead(a);if(!a.CanManage)throw new UnauthorizedAccessException("Project Context management access is required.");}
 private static RepositoryConnectionException Missing()=>new(RepositoryConnectionErrorCodes.NotFound,"Repository connection was not found.");
 private static RepositoryConnectionException Invalid(string m)=>new(RepositoryConnectionErrorCodes.InvalidInput,m);
}